### ISSUE TITLE
Single space for same char repeats apparently not part of Morse standard

### ISSUE THREAD

**Issue by bwagner** [gugupy/morsecodetranslator#1]
[Single space for same char repeats](https://github.com/gugupy/morsecodetranslator#:~:text=Single%20space%20for%20same%20char%20repeats): Doesn't seem to be standard.
[ITU](https://www.itu.int/dms_pubrec/itu-r/rec/m/R-REC-M.1677-1-200910-I!!PDF-E.pdf) doesn't mention it.
Maybe it should be made an option?

**Comment by gugupy** [comment]
@bwagner I am happy that you raised an issue. I was reading about in the google and developed, Even I am not knowing the ITU standard exists. 

I can update based on the standard. Thanks.
